# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

latex: false
fortran: false

matrix:
  include:
    - dist: xenial
      after_success:
        - Rscript -e 'covr::codecov()'
    - os: osx
      brew_packages:
        - freetype
